#!/bin/sh

quoteJSONP=$(curl -s "https://api.forismatic.com/api/1.0/?method=getQuote&lang=en&format=jsonp&jsonp=?" )

quoteJSON=$(echo $quoteJSONP | sed "s/^\?(//g" | sed "s/)$//g")

author=$(echo "$quoteJSON" | jq -r ".quoteAuthor")
quote=$(echo "$quoteJSON" | jq -r ".quoteText")

notify-send "$author" "$quote"
