#!/bin/sh
# Changes the volume level of an audio track
# Signals an update in polybar for the volume module

echo "1st Argument: $1"
echo "2nd Argument: $2"
if [ "$1" = "output-vol" ]; then
  pactl set-sink-mute "$2" false
  pactl set-sink-volume "$2" "$3"
else
  pactl set-sink-mute "$2" toggle
  notify-send "Muted/Unmuted" "$2"
fi

device=$(pactl list sinks | grep 'Name\|Mute\|Volume:' | grep $2 -A 2)
vol=$(echo "$device" | grep "front-left" | awk '{ print $5 }' | tr -d "%")

# Updates volume in bar
polybar-msg hook volume 1
