#!/bin/sh

function open(){
		for var in "$@"
		do
				xdg-open $var 2>/dev/null & disown
		done
}

alias v='nvim';
alias p3='python3';
alias ls='lsd';
alias la='lsd -A';
alias ll='lsd -l';
alias lt='lsd --tree';
alias lla='lsd -lA';
alias wn='python3 /home/akshettrj/.local/bin/wordnet.py';
alias map='npx mapscii';
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"';
alias systemctl='sudo systemctl --no-pager';
alias aptuu='sudo apt update; sudo apt upgrade -y;'
alias fixcur="echo -ne '\e[5 q'"
# alias config='/usr/bin/git --git-dir=/home/akshettrj/repos/dotfiles/ --work-tree=/home/akshettrj'
alias cp='cp -rvi'
alias yarn="yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config"

alias cf='cd /home/akshettrj/coding/codeforces'
alias rcloneCopy='rclone -vv --transfers 3 --stats=15s --drive-chunk-size 128M copy'

alias transmission-daemon='transmission-daemon -w /home/akshettrj/media/torrents'

alias dotfiles='git --git-dir=/home/akshettrj/coding/repos/dotfiles --work-tree=/home/akshettrj'
