#!/bin/sh

export dass="$clg/dass";
export ihs="$clg/ihs";
export ltu="$clg/ltu";
export mdl="$clg/mdl";
export nlp="$clg/nlp";
export lec="$clg/lectures";
export ve="$clg/ve";
export dsa="$clg/dsa";
export at="$clg/at";

alias dass="cd $dass";
alias ihs="cd $ihs";
alias ltu="cd $ltu";
alias mdl="cd $mdl";
alias nlp="cd $nlp";
alias lec="cd $lec";
alias ve="cd $ve";
alias dsa="cd $dsa";
alias at="cd $at";
