#!/bin/sh
emoji=$(cat ~/.scripts/emojiList.txt | dmenu -l 10 -fn "Noto Color Emoji:pixelsize=15" | awk '{print $1}' | tr "\n" " ")
[ "$emoji" != "" ] || exit
echo $emoji | tr "\n" " " | sed "s/\ //g" | copyq add -
copyq select 0 && notify-send "Success" "$emoji copied to clipboard"
